name: Test
on:
 push:
    branches:
      - coverage_test

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint

      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Build test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
            
      - name: Generate coverage report
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: coverage
      - run: find ./ -name "clover.xml" 
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: 2ca1d20f-cd75-4081-8a94-62f6cce3f4fa
          file: ./coverage/clover.xml
